### PR TITLE
history api fix

### PR DESCRIPTION
**Pull request by PuckishRogue91**
This should fix the error after login due to react's strict settings.

### CODE REVIEW

**Comment by rhit-corridg** [comment]
What issue is this?

**Comment by PuckishRogue91** [comment]
There's no issue submitted, but looking at my login attempt on the main page, I get the following error: 
image

**Review by rhit-corridg — CHANGES_REQUESTED** [review]
The function needs to be declared inside of DashboardDropdownMenu or the others

**Comment by rhit-corridg** [comment]
I forgot to mention that, I did get compilation errors when I tried your code and fixed it on my end but didn't update this. Another good reason you should setup your development environment

**Comment by PuckishRogue91** [comment]
Changes are made. And yes, I've been trying to get my dev environment setup. I'm having issues with the Discord login.

**Review by rhit-corridg — APPROVED** [review]

**Pull request merged**
